### ISSUE TITLE
Features - Database

### ISSUE THREAD

**Issue by at-vietpham** [AT-PHPIntership/product-tiki#1]
@at-phuongvu @at-mailuong @at-khadinh @at-trangle
Mọi người cập nhật Requiment và Database vào issue này như hôm qua anh có nói.

**Comment by sinnguyen4991** [comment]
categories.name: nên limit 100 thôi đủ rồi.
- products:
  + `price` nên kiểu `decimal`
  + Thêm trường `quantity` để quản lý số lượng sản phẩm có trong kho.
- `comment` nên thêm 2 trường: `comentable_type`(post, comment), và `commentable_id`: để user có thể vừa comment cho bài `post` vừa trả lời `comment`(multiple level comment)

**Comment by at-xinhnguyen** [comment]
- categories
    + name: nên limit 100 thôi đủ rồi.
- products:
  + `price` nên kiểu `decimal`
  + Thêm trường `quantity` để quản lý số lượng sản phẩm có trong kho.( dùng trigger để quản lý số lượng)
- Nên thêm bảng order_details: 
    + quan hệ orders->order_details(1-n): để user có thể đặt nhiều product 1 lần
`pending` - add `commentable_id` và `commendable_type` vào bảng `comment` thì hay hơn. để sau này query dễ hơn ấy. và rõ ràng hơn nữa. post là post, còn comment là comment.
- users:
    + `username` nên limit 100
    + thêm trường `api_token` : cần thiết cho web api
    + thêm trường `old_password`
    + thêm trường `is_active` để quản lý user đã đc active hay chưa.
    + thêm trường: `last_logined_at` để quản lý lịch sử đăng nhập
- userinfo:
    + nên đổi lại thành user_info: vì đây là 2 từ riêng biệt
    + phone nên : limit 50 
    + bỏ trường `deleted_at` đi vì k cần thiết.
    + thêm `gender`

**Comment by at-huenguyen** [comment]
bọn em đang làm cái này là kiểu bán hàng online phải ko?
Vại giá sản phẩm là riêng cho từng bài đăng hay cố định lun cho 1 sản phẩm?có `rating` cho post nhưng ko thấy chỗ người dùng rate cho bài đăng hè.

**Comment by at-phuongvu** [comment]
* table `posts` của tụi em hiện tại là bao gồm cả `review` và những `comments` bình thường. Trong table `posts` có cái `rating` là rating của người dùng cho sản phẩm rồi ạ.
* table `comments` chính xác là `subcomments` cho 2 loại bài post trên. Chắc chỗ này DB tụi em nên sửa lại tên table là `subcomments` cho ko bị hiểu nhầm ạ :(
